### ISSUE TITLE
text format parsing error

### ISSUE THREAD

**Issue by krisnyse** [micha37-martins/S.M.A.R.T-disk-monitoring-for-Prometheus#11]
Hi,

Node exporter throws out this error message:
level=error collector=textfile msg="failed to collect textfile data" file=smart_metrics.prom err="failed to parse textfile data from \"/var/lib/node_exporter/textfile_collector/smart_metrics.prom\": text format parsing error in line 6: expected float as value, got \"0,000000e+00\""

Line 6 in the prom file looks like this:
smartmon_current_pending_sector_raw_value{disk="/dev/sda",type="sat",smart_id="197"} 0,000000e+00

**Comment by vivlab** [comment]
Hi, 

Any advice for this problem ? I have the same issue.

Regards

**Comment by micha37-martins** [comment]
I also had this and it should now be fixed or properly handled after the rewrite.
