### ISSUE TITLE
Several metrics not working with Ubuntu 18.04 (smartmontools=7.0-0ubuntu1~ubuntu18.04.1)

### ISSUE THREAD

**Issue by YanickNoblanc** [micha37-martins/S.M.A.R.T-disk-monitoring-for-Prometheus#7]
Hi, is there a more up to date version of this script adapted to smartmontools=7.0-0ubuntu1~ubuntu18.04.1 ?
Currentl version uses several metrics that do not match smartctl output 

    smartmon_percent_lifetime_remain
    smartmon_start_stop_count_raw_value
    smartmon_total_host_sector_write_raw_value
    smartmon_load_cycle_count_raw_value

**Comment by micha37-martins** [comment]
This should work with up to date version of the script and recent UBUNTU.
