### ISSUE TITLE
Adding Attribute Aliases

### ISSUE THREAD

**Issue by norsemangrey** [micha37-martins/S.M.A.R.T-disk-monitoring-for-Prometheus#9]
This is more of an improvement suggestion than an issue I guess. 

I just started using the script and it works great, however, I see that the same SMART attributes might have slightly different names on different devices. I could extend on the attributes array, but I would really like same attributes from different drives to be logged together, so I wonder would it be possible to modify the script so that one could add "aliases" for the attributes the script is looking for in the smartctl output? I do not have much enough experience with bash to do it myself unfortunately.

**Comment by micha37-martins** [comment]
Thanks for this idea. At the moment I want to keep it as it is but feel free to hand in a PR.
